"""
Django settings for mi_cv project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from django.utils.translation import gettext_lazy as _
from decouple import config, Csv
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ==========================================================
# CONFIGURACION SENSIBLE
# ==========================================================
# Todos los secretos se leen del archivo .env, que NO esta en el
# repositorio. Ver .env.example para la plantilla.
# Nunca escribas claves directamente en este archivo.

SECRET_KEY = config('SECRET_KEY')

OPENAI_API_KEY = config('OPENAI_API_KEY', default='')

# DEBUG es False por defecto: si olvidas definirlo en produccion,
# el sitio falla del lado seguro en lugar de exponer los settings.
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())


# Application definition

DJANGO_APPS = [
    'modeltranslation',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

LOCAL_APPS= [
    "iachat_app.apps.IachatAppConfig",
    "portafolio_app.apps.PortafolioAppConfig",
    "site_app.apps.SiteAppConfig",
    "user_app.apps.UserAppConfig",
    "blog_app.apps.BlogAppConfig",
]

THIRD_APPS = [
    'widget_tweaks', 
    'django_recaptcha',   
]

INSTALLED_APPS = DJANGO_APPS + LOCAL_APPS + THIRD_APPS

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Sirve los archivos estaticos comprimidos y cacheados sin necesidad
    # de nginx. Debe ir justo despues de SecurityMiddleware.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mi_cv.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mi_cv.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME', default='cv_edgar'),
        'USER': config('DB_USER', default='postgres'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='5432'),
        # Reutiliza la conexion durante 60s en lugar de abrir una nueva
        # en cada request.
        'CONN_MAX_AGE': 60,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static'
]

STATIC_ROOT = BASE_DIR / 'staticfiles'


MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'user_app.CustomUser'

LOGIN_URL = '/user/login/' 
LOGIN_REDIRECT_URL = 'es/'

# CATPCHA SETTINGS

# claves de Google (leidas desde .env)
RECAPTCHA_PUBLIC_KEY = config('RECAPTCHA_PUBLIC_KEY', default='')
RECAPTCHA_PRIVATE_KEY = config('RECAPTCHA_PRIVATE_KEY', default='')

# Evita errores de HTTPS en desarrollo (localhost)
OS_RECAPTCHA_Use_SSL = True

# Lenguajes 

LANGUAGE_CODE = 'es' # Idioma por defecto

LANGUAGES = [
    ('es', _('Español')),
    ('en', _('English')),
    ('ru', _('Russian')),
]

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]

USE_I18N = True
USE_L10N = True


# ==========================================================
# ARCHIVOS ESTATICOS EN PRODUCCION (WhiteNoise)
# ==========================================================

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}


# ==========================================================
# CACHE
# ==========================================================
# Usada para cachear las respuestas del chat de IA y no pagar dos veces
# por la misma pregunta. En produccion conviene sustituirla por Redis.

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'mi-cv-cache',
        'TIMEOUT': 60 * 60 * 24,
        'OPTIONS': {'MAX_ENTRIES': 1000},
    }
}


# ==========================================================
# LIMITES DEL CHAT DE IA
# ==========================================================

# Longitud maxima del mensaje del usuario. Evita que alguien envie
# textos gigantes para inflar el consumo de tokens.
IACHAT_MAX_MESSAGE_LENGTH = 300

# Limites de peticiones por IP.
IACHAT_RATE_PER_MINUTE = '5/m'
IACHAT_RATE_PER_DAY = '40/d'


# ==========================================================
# SEGURIDAD
# ==========================================================

# Cabeceras que aplican siempre.
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = 'same-origin'
X_FRAME_OPTIONS = 'DENY'

# Dominios autorizados a enviar formularios POST (necesario tras HTTPS).
CSRF_TRUSTED_ORIGINS = config(
    'CSRF_TRUSTED_ORIGINS',
    default='http://localhost:8000,http://127.0.0.1:8000',
    cast=Csv(),
)

if not DEBUG:
    # Fuerza HTTPS en todo el sitio.
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

    # HSTS: el navegador recuerda durante un anio que este dominio es
    # solo HTTPS. Empieza con un valor bajo (ej. 3600) si no estas seguro,
    # porque es dificil de revertir.
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    # Las cookies solo viajan por HTTPS y no son legibles desde JavaScript.
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True


# ==========================================================
# LOGGING
# ==========================================================
# Los errores van al log del servidor, nunca a la pantalla del visitante.
# Importante: no registramos el contenido de los mensajes de los usuarios.

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {
            'format': '[{asctime}] {levelname} {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'iachat_app': {
            'handlers': ['console'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
    },
}

