# Generated by Django 5.2.8 on 2025-11-22 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del Proyecto')),
                ('imagen', models.ImageField(upload_to='portfolio/', verbose_name='Imagen de portada')),
                ('objetivo', models.TextField(verbose_name='Objetivo')),
                ('descripcion', models.TextField(verbose_name='Resumen del proyecto')),
                ('tecnologias', models.CharField(help_text='Ej: Python, Django, SQL', max_length=200, verbose_name='Tecnologías usadas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
