# Generated by Django 5.2.8 on 2025-11-24 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='descripcion_en',
            field=models.TextField(null=True, verbose_name='Resumen del proyecto'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='descripcion_es',
            field=models.TextField(null=True, verbose_name='Resumen del proyecto'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='descripcion_ru',
            field=models.TextField(null=True, verbose_name='Resumen del proyecto'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='objetivo_en',
            field=models.TextField(null=True, verbose_name='Objetivo'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='objetivo_es',
            field=models.TextField(null=True, verbose_name='Objetivo'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='objetivo_ru',
            field=models.TextField(null=True, verbose_name='Objetivo'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='titulo_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Título del Proyecto'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='titulo_es',
            field=models.CharField(max_length=200, null=True, verbose_name='Título del Proyecto'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='titulo_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Título del Proyecto'),
        ),
    ]
