# Generated by Django 5.2.8 on 2026-08-29 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio_app', '0003_imagenes_a_webp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyectoImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='portfolio/', verbose_name='Imagen')),
                ('titulo', models.CharField(blank=True, help_text='Texto alternativo / pie de imagen.', max_length=200, verbose_name='Descripción (opcional)')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Posición en el slider. Menor número aparece primero.', verbose_name='Orden')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='portafolio_app.proyecto', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Imagen del proyecto',
                'verbose_name_plural': 'Imágenes del proyecto (slider)',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
