# Generated by Django 5.2.8 on 2026-09-18 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio_app', '0004_proyectoimagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyectoEnlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Lo que se muestra. Ej: GitHub, Demo en vivo, Artículo.', max_length=100, verbose_name='Texto del enlace')),
                ('url', models.URLField(max_length=500, verbose_name='URL')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Posición. Menor número aparece primero.', verbose_name='Orden')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enlaces', to='portafolio_app.proyecto', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Enlace del proyecto',
                'verbose_name_plural': 'Enlaces del proyecto',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
