# Generated by Django 5.2.8 on 2025-11-18 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='nombre',
        ),
    ]
