# Generated by Django 5.2.8 on 2025-11-21 23:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_customuser_empresa_customuser_profesion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cedula',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='La cédula debe contener solo números.', regex='^\\d+$')]),
        ),
    ]
