# Generated by Django 5.2.8 on 2026-08-29 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_alter_customuser_cedula'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='token_limit',
            field=models.PositiveIntegerField(default=1000, help_text='Tope de tokens que este usuario puede gastar en el chat IA.', verbose_name='Límite de tokens IA'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tokens_usados',
            field=models.PositiveIntegerField(default=0, help_text='Tokens ya consumidos por este usuario en el chat IA.', verbose_name='Tokens IA usados'),
        ),
    ]
